### ISSUE TITLE
error and warning on install

### ISSUE THREAD

**Issue by dogslife** [prettymuchbryce/flashio#1]
@prettymuchbryce Hi just trying out the flashio and via the npm I keep getting the following
+-- express@4.13.4
+-- flashio@0.0.2  extraneous
`-- policyfile@0.0.5  invalid

npm WARN flashsocket-sample@0.1.0 No repository field
npm WARN flashsocket-sample@0.1.0 No license field.

is this normal?

**Comment by prettymuchbryce** [comment]
I'm sorry you're having trouble. I haven't worked on this project in about 2 years.

That being said those errors don't look related to flashio, which doesn't have any external dependencies. It looks to me like those warnings are due to a project call `flashsocket-sample`, and are just warnings around missing package.json fields. I'm unsure about the `policyfile` invalid error.

I would recommend you find another project that suits your needs as I am unable to provide support for this project anymore. Sorry about that. Good luck!
